gazebo:

  commands:
    names:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - WR_FLE
      - WR_DEV
      - WR_PRO

  joint_states:
    topic: /sensors/joint_states
    queue_size: 100
    names:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - WR_FLE
      - WR_DEV
      - WR_PRO
      
    default_positions:
      - deg(0.0)
      - deg(0.0)
      - deg(0.0)
      - deg(0.0)
      - deg(0.0)
      - deg(0.0)

  contact_forces:
    topics:
      - /sensors/contact_force_lf_foot
      - /sensors/contact_force_rf_foot
      - /sensors/contact_force_lh_foot
      - /sensors/contact_force_rh_foot
    queue_sizes:
      - 100
      - 100
      - 100
      - 100
    linear_velocity_threshold: 0.6

  quadruped_state_throttle:
    decimation: 40
  quadruped_state:
    publish: true
    topic: /state_estimator/quadruped_state
    queue_size: 10
    min_frequency_rate: 0.1
    max_frequency_rate: 0.1
    pose:
      frame: base
    pose_in_odom:
      topic: /state_estimator/pose_in_odom
      frame: odom
    twist:
      topic: /state_estimator/twist
      frame: base

  seactuators:
    topic: /locomotion_controller/actuators
    queue_size: 100

  set_robot_pose:
    service: set_robot_pose
    
