gazebo:

  commands:
    names:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE

  joint_states:
    topic: /sensors/joint_states
    queue_size: 100
    names:
      - LF_HAA
      - LF_HFE
      - LF_KFE
      - RF_HAA
      - RF_HFE
      - RF_KFE
      - LH_HAA
      - LH_HFE
      - LH_KFE
      - RH_HAA
      - RH_HFE
      - RH_KFE
      
    default_positions:
      - deg(3)
      - deg(90)
      - deg(-160)
      - deg(-3)
      - deg(90)
      - deg(-160)
      - deg(3)
      - deg(-90)
      - deg(160)
      - deg(-3)
      - deg(-90)
      - deg(160)

  contact_forces:
    topics:
      - /sensors/contact_force_lf_foot
      - /sensors/contact_force_rf_foot
      - /sensors/contact_force_lh_foot
      - /sensors/contact_force_rh_foot
    queue_sizes:
      - 100
      - 100
      - 100
      - 100
    linear_velocity_threshold: 0.6

  quadruped_state:
    publish: true
    topic: /state_estimator/quadruped_state
    queue_size: 100
    min_frequency_rate: 0.1
    max_frequency_rate: 0.1
    pose:
      frame: base
    pose_in_odom:
      topic: /state_estimator/pose_in_odom
      frame: odom
    twist:
      topic: /state_estimator/twist
      frame: base

  seactuators:
    topic: /locomotion_controller/actuators
    queue_size: 100
    
